name: Build and Release (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

# Permissões necessárias para que o GITHUB_TOKEN possa criar releases e fazer upload de assets.
# Sem 'contents: write' a action de criação de release pode falhar com
# "Resource not accessible by integration" em algumas configurações do repositório/organização.
permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build on Windows and create Release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create virtualenv
        run: python -m venv .venv

      - name: Install dependencies
        run: .\.venv\Scripts\python -m pip install --upgrade pip && .\.venv\Scripts\python -m pip install -r requirements.txt

      - name: Run build.bat (PyInstaller)
        shell: cmd
        run: .\build.bat

      - name: Upload exe as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: CatalogoDePecas-exe
          path: dist\CatalogoDePecas.exe

      - name: Create GitHub Release and upload asset (PowerShell)
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Chamamos o script PowerShell que cria a release e faz upload do asset.
          $tag = "${{ github.ref_name }}"
          $releaseName = "${{ github.ref_name }}"
          $body = "Automated release generated by GitHub Actions."
          $assetPath = 'dist\CatalogoDePecas.exe'
          if (-not (Test-Path $assetPath)) {
            Write-Error "Asset not found: $assetPath"
            exit 1
          }
          $scriptPath = Join-Path $env:GITHUB_WORKSPACE 'scripts\create_release.ps1'
          Write-Host "Looking for script at: $scriptPath"
          if (-not (Test-Path $scriptPath)) {
            Write-Error "Script not found: $scriptPath"
            Write-Host "Repository root listing (first 200 entries):"
            Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Force -ErrorAction SilentlyContinue | Select-Object FullName,Length | Select-Object -First 200 | Format-Table -AutoSize
            exit 1
          }
          Write-Host "Creating release $tag and uploading asset $assetPath using script $scriptPath"
          & "$scriptPath" -TagName $tag -ReleaseName $releaseName -Body $body -AssetPath $assetPath -Repo "ricardofebronio19/CATALOGOGERAL"
